[project]
name = "gui-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.9.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.7.7",
]
